// performance/helpers/data.js
// Deterministic-enough test-data generators for k6's goja runtime.
// Note: Date.now() and Math.random() are blocked in workflow scripts
// but ARE available in k6 VU code, so these functions are safe to call
// from flow functions (not from setup() return values).

const FIRST = ['Alex', 'Sam', 'Jordan', 'Taylor', 'Morgan', 'Casey', 'Riley', 'Drew', 'Avery', 'Quinn'];
const LAST  = ['Smith', 'Jones', 'Brown', 'Davis', 'Wilson', 'Moore', 'Taylor', 'Anderson', 'Thomas', 'Jackson'];

export function randomName() {
  return `${FIRST[Math.floor(Math.random() * FIRST.length)]} ${LAST[Math.floor(Math.random() * LAST.length)]}`;
}

export function randomStr(len) {
  len = len || 8;
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let s = '';
  for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}

export function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Return a random think-time in seconds between min and max.
 * Pass the result to sleep().
 */
export function thinkTime(min, max) {
  min = (min === undefined) ? 1 : min;
  max = (max === undefined) ? 3 : max;
  return min + Math.random() * (max - min);
}

/** Pick a random element from an array; returns null if empty. */
export function pick(arr) {
  if (!arr || arr.length === 0) return null;
  return arr[Math.floor(Math.random() * arr.length)];
}

// ── Payload factories ─────────────────────────────────────────

export function assignmentPayload(courseId) {
  return {
    title: `Perf-Test Assignment ${randomStr(6)}`,
    description: 'Auto-generated by performance test suite. Safe to delete.',
    course_id: courseId || undefined,
    max_marks: randomInt(50, 100),
  };
}

export function notificationPayload(userId) {
  return {
    user_id: userId,
    title: 'Perf Test Notification',
    message: 'Sent during automated performance testing.',
    type: 'info',
    category: 'system',
  };
}

export function messagePayload(receiverId) {
  const msgs = [
    'When is the next live class?',
    'Can you help me with the assignment?',
    'I have a question about the course content.',
    'Could you review my submission?',
  ];
  return { receiver_id: receiverId, content: pick(msgs) };
}

export function aiSessionPayload() {
  const tracks = ['dsa', 'system-design', 'web', 'python', 'java'];
  const diffs  = ['Easy', 'Medium', 'Hard'];
  return {
    track: pick(tracks),
    difficulty: pick(diffs),
    duration_mins: randomInt(15, 60),
    score: randomInt(40, 100),
    feedback: 'Completed during performance test.',
  };
}

// A 1×1 white PNG in base64 — safe to upload; tiny footprint
export const SAMPLE_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk' +
  '+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';

export function uploadPayload() {
  return {
    file:     SAMPLE_PNG_BASE64,
    filename: `perf-test-${randomStr(6)}.png`,
    folder:   'perf-test',
    bucket:   'uploads',
  };
}
