// performance/helpers/summary.js
// Generates HTML + JSON + stdout summary for handleSummary().
// Import buildSummary() in each scenario file.

import { textSummary } from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';

/**
 * Call from handleSummary(data) in a scenario file:
 *   export function handleSummary(data) { return buildSummary(data, 'load'); }
 */
export function buildSummary(data, scenarioName) {
  const ts   = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const base = `${scenarioName}-${ts}`;

  return {
    [`reports/${base}.json`]: JSON.stringify(data, null, 2),
    [`reports/${base}.html`]: renderHTML(data, scenarioName),
    stdout: textSummary(data, { indent: '  ', enableColors: true }),
  };
}

// ── Private HTML renderer ─────────────────────────────────────

function mv(data, metric, stat) {
  try {
    var v = data.metrics[metric].values[stat];
    return (v !== undefined && v !== null) ? Number(v).toFixed(2) : 'N/A';
  } catch (_) { return 'N/A'; }
}

function pct(data, metric, stat) {
  var v = mv(data, metric, stat);
  return v === 'N/A' ? 'N/A' : (parseFloat(v) * 100).toFixed(2) + '%';
}

function renderHTML(data, scenarioName) {
  var thresholds  = data.thresholds || {};
  var failedKeys  = Object.keys(thresholds).filter(function(k) { return !thresholds[k].ok; });
  var passed      = failedKeys.length === 0;
  var statusColor = passed ? '#22c55e' : '#ef4444';
  var statusText  = passed ? 'ALL THRESHOLDS PASSED' : 'THRESHOLDS FAILED (' + failedKeys.length + ')';

  var kpis = [
    { label: 'p95 Latency',    value: mv(data, 'http_req_duration', 'p(95)') + ' ms' },
    { label: 'p99 Latency',    value: mv(data, 'http_req_duration', 'p(99)') + ' ms' },
    { label: 'Median Latency', value: mv(data, 'http_req_duration', 'med')   + ' ms' },
    { label: 'Max Latency',    value: mv(data, 'http_req_duration', 'max')   + ' ms' },
    { label: 'RPS',            value: mv(data, 'http_reqs', 'rate')           },
    { label: 'Total Requests', value: mv(data, 'http_reqs', 'count')          },
    { label: 'Error Rate',     value: pct(data, 'http_req_failed', 'rate')    },
    { label: 'Peak VUs',       value: mv(data, 'vus_max', 'max')              },
  ];

  var kpiHTML = kpis.map(function(k) {
    return '<div class="card"><div class="label">' + k.label + '</div><div class="val">' + k.value + '</div></div>';
  }).join('');

  var allThresholdRows = Object.keys(thresholds).map(function(k) {
    var ok = thresholds[k].ok;
    return '<tr><td>' + k + '</td><td class="' + (ok ? 'ok' : 'fail') + '">' + (ok ? 'PASS' : 'FAIL') + '</td></tr>';
  }).join('');

  return '<!DOCTYPE html>\n' +
'<html lang="en">\n' +
'<head>\n' +
'<meta charset="UTF-8"/>\n' +
'<meta name="viewport" content="width=device-width,initial-scale=1"/>\n' +
'<title>k6 Report — ' + scenarioName + '</title>\n' +
'<style>\n' +
'*{box-sizing:border-box;margin:0;padding:0}\n' +
'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#0f172a;color:#e2e8f0;padding:2rem}\n' +
'h1{font-size:1.75rem;font-weight:700;margin-bottom:.25rem}\n' +
'.sub{color:#94a3b8;font-size:.9rem;margin-bottom:1.5rem}\n' +
'.badge{display:inline-block;padding:.35rem 1rem;border-radius:9999px;font-weight:700;font-size:.9rem;color:#fff;background:' + statusColor + ';margin-bottom:2rem}\n' +
'.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:1rem;margin-bottom:2rem}\n' +
'.card{background:#1e293b;border-radius:.75rem;padding:1.25rem}\n' +
'.label{font-size:.7rem;text-transform:uppercase;letter-spacing:.06em;color:#94a3b8;margin-bottom:.4rem}\n' +
'.val{font-size:1.5rem;font-weight:700;color:#f1f5f9}\n' +
'h2{font-size:1rem;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em;margin:1.5rem 0 .75rem}\n' +
'table{width:100%;border-collapse:collapse;background:#1e293b;border-radius:.75rem;overflow:hidden;margin-bottom:1.5rem}\n' +
'th,td{padding:.65rem 1rem;font-size:.82rem;text-align:left}\n' +
'th{background:#0f172a;color:#64748b;font-size:.7rem;text-transform:uppercase;letter-spacing:.05em}\n' +
'tr:nth-child(even){background:#243147}\n' +
'.ok{color:#4ade80;font-weight:600} .fail{color:#f87171;font-weight:600}\n' +
'footer{color:#334155;font-size:.72rem;margin-top:2rem}\n' +
'</style>\n' +
'</head>\n' +
'<body>\n' +
'<h1>StayKaro LMS — Performance Report</h1>\n' +
'<p class="sub">Scenario: <strong>' + scenarioName + '</strong></p>\n' +
'<div class="badge">' + statusText + '</div>\n' +
'<div class="grid">' + kpiHTML + '</div>\n' +
'<h2>Thresholds</h2>\n' +
'<table><thead><tr><th>Threshold</th><th>Result</th></tr></thead><tbody>' + allThresholdRows + '</tbody></table>\n' +
'<footer>Generated by StayKaro k6 Performance Suite</footer>\n' +
'</body>\n' +
'</html>';
}
